# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d57758a6469311d1db969198fad198a57fa5e9d3f5e75ce4ee10ce2539458e8d60226412bb6ff366617d4ef65b8dc8417954e91b451ba5b858b12ab7497bb5f

test:
  secret_key_base: 9d92c82a31f99b846f1fb8193df4b85844871f8f219cb66d9576df7c2e57ec0ccc25102fe60d5cd548abf509049cbb2c4fb045908aaef20b796cc5e8dffe9f9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
